apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Staging-specific patches
patches:
  - path: api-staging.yaml
  - path: configmap-staging.yaml

images:
  - name: ml-pipeline/api
    newTag: staging

replicas:
  - name: ml-pipeline-api
    count: 2

namespace: ml-pipeline-staging
