apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - api-production.yaml
  - configmap-production.yaml



images:
- name: ml-pipeline/api
  newTag: v1.0.0

replicas:
- name: ml-pipeline-api
  count: 5

namespace: ml-pipeline-prod