apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - mlflow.yaml
  - api.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/name: ml-pipeline
  app.kubernetes.io/instance: ml-pipeline-platform
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: ml-platform
  app.kubernetes.io/part-of: ml-pipeline-platform

namespace: ml-pipeline

images:
- name: ml-pipeline/api
  newTag: latest